// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCugcfycieb6Ge5hM-zYIGtPCYJhISnO6s',
    appId: '1:623158656176:web:774ef20de9c3d4da494f75',
    messagingSenderId: '623158656176',
    projectId: 'fir-2d6fc',
    authDomain: 'fir-2d6fc.firebaseapp.com',
    storageBucket: 'fir-2d6fc.appspot.com',
    measurementId: 'G-CNEBDB6T27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDDQoS5uZWp59rRHK06absgL3fJnxhhA',
    appId: '1:623158656176:android:c9fe07db9d5651bf494f75',
    messagingSenderId: '623158656176',
    projectId: 'fir-2d6fc',
    storageBucket: 'fir-2d6fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHcxoHkv6XCm5eIuzhW1OHs5zS8noqI4M',
    appId: '1:623158656176:ios:e4a246e704210c27494f75',
    messagingSenderId: '623158656176',
    projectId: 'fir-2d6fc',
    storageBucket: 'fir-2d6fc.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHcxoHkv6XCm5eIuzhW1OHs5zS8noqI4M',
    appId: '1:623158656176:ios:e4a246e704210c27494f75',
    messagingSenderId: '623158656176',
    projectId: 'fir-2d6fc',
    storageBucket: 'fir-2d6fc.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCugcfycieb6Ge5hM-zYIGtPCYJhISnO6s',
    appId: '1:623158656176:web:31d9a7d268c8c04e494f75',
    messagingSenderId: '623158656176',
    projectId: 'fir-2d6fc',
    authDomain: 'fir-2d6fc.firebaseapp.com',
    storageBucket: 'fir-2d6fc.appspot.com',
    measurementId: 'G-7XW7PCKJ0C',
  );
}
